name: ynov-2025-b1-symfony

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:12.0.2-ubi10
    container_name: ynov-2025-b1-symfony-database
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-root_password}
      - MARIADB_USER=${MARIADB_USER:-app}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-app_password}
      - MARIADB_DATABASE=${MARIADB_DATABASE:-app}
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - ynov-2025-b1-symfony_network
    ports:
      - 3306:3306
    restart: unless-stopped
  ###< doctrine/doctrine-bundle ###

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: ynov-2025-b1-symfony-phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
      - PMA_USER=${MARIADB_USER:-app}
      - PMA_PASSWORD=${MARIADB_PASSWORD:-app_password}
    depends_on:
      - database
    networks:
      - ynov-2025-b1-symfony_network
    restart: unless-stopped

  apache:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ynov-2025-b1-symfony-apache
    volumes:
      - .:/var/www/
      - ./docker/apache/apache.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./docker/apache/php.ini:/usr/local/etc/php/conf.d/php.custom.ini
      - ./docker/apache/.htaccess:/var/www/public/.htaccess
    ports:
      - 8000:80
    depends_on:
      - database
    networks:
      - ynov-2025-b1-symfony_network
    restart: unless-stopped

networks:
  ynov-2025-b1-symfony_network:
    driver: bridge

volumes:
  database_data:
    driver: local